# Default configuration settings

# Application settings
app:
  name: "Ava AI Assistant"
  version: "1.0.0"
  debug: false
  log_level: "INFO"

# Paths configuration
paths:
  memory_dir: "memory"
  secure_info_file: "memory/david_info_secure.txt"
  logs_dir: "logs"

# Chat interface settings
interface:
  theme: "dark"
  command_prefix: "/"
  prompt: "You: "

# Memory settings
memory:
  max_memories: 5
  importance_threshold: 0.5
  memory_file_format: "json"
  index_file: "memory_index.json"
  backup_interval_hours: 24

# Voice settings
voice:
  enabled: true
  input_device: "default"
  output_device: "default"
  language: "en-US"
  timeout_seconds: 5
  energy_threshold: 300

# API settings (template - fill in your own values)
api:
  openai:
    model: "gpt-4"
    temperature: 0.7
    max_tokens: 150
    # Add your API key to .env file, not here
    timeout_seconds: 30

# UI Component settings
ui:
  window:
    width: 1200
    height: 800
    min_width: 800
    min_height: 600
  components:
    chat_display:
      max_messages: 100
      timestamp_format: "%H:%M:%S"
    task_panel:
      max_tasks: 10
      refresh_interval_ms: 1000
    toolbar:
      show_icons: true
      icon_size: 24

# Service settings
services:
  chat:
    model: "gpt-4"
    max_history: 50
    timeout_seconds: 30
    retry_attempts: 3
  memory:
    storage_path: "./memory"
    max_size: 1000
    backup_interval_hours: 24
    cleanup_threshold: 0.8
  voice:
    enabled: true
    input_device: "default"
    output_device: "default"
    timeout_seconds: 5
    energy_threshold: 300

# Plugin settings
plugins:
  enabled: true
  auto_load: true
  directory: "plugins"
  settings:
    rss:
      update_interval: 300
      max_items: 10
    git:
      auto_backup: true
      backup_interval: 3600
    screen:
      capture_quality: 0.8
      max_screenshots: 100

# Command settings
commands:
  memory:
    aliases: ["memories", "recall"]
    description: "Display recent memories"
  help:
    aliases: ["?", "commands"]
    description: "Show available commands"
  clear:
    aliases: ["cls", "clean"]
    description: "Clear chat window"
